# Generated by Django 3.0.6 on 2020-05-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foliopage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tagline',
            new_name='overview',
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, default='images/avatar.svg', upload_to='images'),
        ),
    ]
