# Generated by Django 3.0.6 on 2020-05-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foliopage', '0003_auto_20200515_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skilltag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='skills',
            field=models.ManyToManyField(to='foliopage.Skilltag'),
        ),
    ]
