# Generated by Django 3.0.6 on 2020-05-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foliopage', '0005_auto_20200515_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='skills',
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.CharField(default='django', max_length=100),
            preserve_default=False,
        ),
    ]
