# Generated by Django 3.0.6 on 2020-05-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foliopage', '0006_auto_20200515_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skilltag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='skills',
        ),
    ]
