# Generated by Django 3.0.6 on 2020-05-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foliopage', '0007_auto_20200515_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(to='foliopage.Skilltag'),
        ),
    ]
