# Generated by Django 3.0.6 on 2020-05-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foliopage', '0008_project_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='about',
            field=models.TextField(default='About', max_length=1000),
            preserve_default=False,
        ),
    ]
