# Generated by Django 3.0.6 on 2020-05-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foliopage', '0009_person_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skilltag',
            old_name='skill',
            new_name='skilltag',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('priority', models.IntegerField(default=0)),
                ('skills', models.ManyToManyField(to='foliopage.Skilltag')),
            ],
        ),
    ]
