# Generated by Django 3.0.6 on 2020-05-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foliopage', '0010_auto_20200515_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skilltag',
            old_name='skilltag',
            new_name='skill',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skills',
        ),
    ]
