# Generated by Django 3.0.6 on 2020-05-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foliopage', '0011_auto_20200515_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['priority']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['priority']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='skills',
        ),
        migrations.AddField(
            model_name='project',
            name='project_skills',
            field=models.ManyToManyField(blank=True, null=True, to='foliopage.Skilltag'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('priority', models.IntegerField(default=0)),
                ('experience_skills', models.ManyToManyField(blank=True, null=True, to='foliopage.Skilltag')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
