# Generated by Django 3.0.6 on 2020-05-16 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foliopage', '0012_auto_20200516_0331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'Person'},
        ),
    ]
