# Generated by Django 3.0.6 on 2020-05-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foliopage', '0013_auto_20200516_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_skills',
            field=models.ManyToManyField(blank=True, to='foliopage.Skilltag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_skills',
            field=models.ManyToManyField(blank=True, to='foliopage.Skilltag'),
        ),
    ]
