# Generated by Django 3.0.6 on 2020-05-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foliopage', '0014_auto_20200516_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.IntegerField(unique=True),
        ),
    ]
