# Generated by Django 3.0.6 on 2020-05-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foliopage', '0015_auto_20200516_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
