# Generated by Django 3.0.6 on 2020-05-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foliopage', '0016_person_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
