# Generated by Django 3.0.6 on 2020-05-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foliopage', '0017_auto_20200516_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('name_fa', models.CharField(max_length=500)),
            ],
        ),
    ]
