# Generated by Django 3.0.6 on 2020-05-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foliopage', '0019_socialmedia_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.FileField(blank=True, default='images/avatar.svg', upload_to='images'),
        ),
    ]
